import io.netty.resolver.dns.DnsResolveContext.DnsResolveContextException;
public class FunctionUse16431 {
public void funcUse() {
DnsResolveContextException dnsresolvecontextexception = new DnsResolveContextException();
dnsresolvecontextexception.fillInStackTrace();
}
}